openapi: 3.1.0
info:
  title: Timetable Manager API specification
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /academicYears: 
    get: 
      summary: Get all academic years by userId.
  /subjects:
    get:
      summary: Get all subjects by department and all multi-disciplinary subjects.
  /classrooms:
    get:
      summary: Get all classrooms by academicYearId.
  /teachers:
    get:
      summary: Get all teachers by academicYearId.
  /batches:
    get:
      summary: Get all batches by academicYearId.
  /divisions:
    get:
      summary: Get all divisions by departmentId.
  /departments:
    get:
      summary: Get all departments by batchId.
  /divisionTimetable:
   get:
    summary: Get timetable information by divisionId.
  /teacherTimetable:
    get:
      summary: Get timetable information by teacherId.
  /classroomTimetable:
    get:
      summary: Get timetable information by classroomId.
  /availableTeachers:
    get:
      summary: Get all available teachers by slotId.
  /availableClassrooms:
    get:
      summary: Get all available classrooms by slotId.
  /slotData:
    patch:
      summary: Needs previous slotId, classroomIds[] and new SlotData[slotId, subdivisionIds[], subjectId, teacherId, classroomIds[]].
  